// react/31/src/components/leftSlide.js
import React from "react";
export default class LeftSlide extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            leftSlideItems:[
                {
                    text:"美女"
                },
                {
                    text:"大美女"
                },
                {
                    text:"超级大美女"
                },
                {
                    text:"超级超级大美女"
                }
            ]
        }
    }
    render(){
        const { leftSlideItems } = this.state;
        const { transform:{ translate,value },slideStyle:{ slideLeftWidth,itemWidth,left,top } } = this.props;
        return (
            <div className="left-slide" style={{ transform:`${ translate }(${ value })`,width:slideLeftWidth,left:left,top:top }}>
                {
                    leftSlideItems.map((slide,index) => (
                        <div key={slide.text + index} className="left-slide-item" style={{ width:itemWidth }}>
                            <h1>美女{(index + 1)}</h1>
                            <p>这是一个{ slide.text }</p>
                        </div>
                    ))
                }
            </div>
        )
    }
}

// vue/49/src/components/LeftSlide.vue
<template>
    <div 
        class="ds-left-slide"
        :style="{ 
            'transform':`${ transform.translate }(${ transform.value })`,
            'width':slideStyle.slideLeftWidth,
            'left':slideStyle.left,
            'top':slideStyle.top 
        }"
    >
        <div 
            v-for="(item,index) in leftSlideItems" 
            :key="item.text + index" 
            class="ds-left-slide-item" 
            :style="{'width':slideStyle.itemWidth }"
        >
            <async-title>美女{{ index + 1}}</async-title>
            <p>这是一个{{ item.text }}</p>
        </div>
    </div>
</template>
<script lang="ts" setup>
    import { computed, defineAsyncComponent, ref } from 'vue';
    const AsyncTitle = defineAsyncComponent(() => import("./Title.vue"));
    const leftSlideItems = ref<Array<{text:string}>>([
        {
            text:"美女"
        },
        {
            text:"大美女"
        },
        {
            text:"超级大美女"
        },
        {
            text:"超级超级大美女"
        }
    ]);
    const props = defineProps({
        transform:{
            type:Object,
            default:() => ({
                translate:"",
                value:""
            })
        },
        slideStyle:{
            type:Object,
            default:() => ({
                slideLeftWidth:"",
                itemWidth:"",
                left:"",
                top:""
            })
        }
    });
    const transform = computed(() => props.transform);
    const slideStyle = computed(() => props.slideStyle);
    console.log(slideStyle.value)
</script>
