// react/31/src/components/rightSlide.js
import React from "react";
const image_url = "https://www.eveningwater.com/my-web-projects/jQuery/12/img/";
export default class RightSlide extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            rightSlideItems:[
                "1.jpg",
                "2.jpg",
                "3.jpg",
                "4.jpg",
            ]
        }
    }
    render(){
        const { rightSlideItems } = this.state;
        const { transform:{ translate,value },slideStyle:{ slideRightWidth,itemWidth} } = this.props;
        return (
            <div className="right-slide" style={{ transform:`${ translate }(${ value })`,width:slideRightWidth  }}>
                {
                    rightSlideItems.map((slide,index) => (
                        <div key={slide + index} style={{ backgroundImage:`url(${image_url + slide})`,width:itemWidth }} className="right-slide-item"></div>
                    ))
                }
            </div>
        )
    }
}

// vue/49/src/components/RightSlide.vue
<template>
    <div class="ds-right-slide" 
    :style="{ 
        'transform':`${ transform.translate }(${ transform.value })`,
        'width':slideStyle.slideRightWidth
    }">
        <div 
            class="ds-right-slide-item" 
            v-for="(item,index) in imageItems" 
            :key="item.src + index"
            :style="{
                backgroundImage:`url(${image_url+item.src})`,
                width:slideStyle.itemWidth
            }"
        ></div>
    </div>
</template>
<script lang="ts" setup>
    import { computed, ref } from 'vue';
    const image_url = computed(() => "https://www.eveningwater.com/my-web-projects/jQuery/12/img/");
    const imageItems = ref<Array<{ src:string }>>([]);
    for(let i = 1;i <= 4;i++){
        imageItems.value.push({ src:`${i}.jpg` });
    }
    const props = defineProps({
        transform:{
            type:Object,
            default:() => ({
                translate:"",
                value:""
            })
        },
        slideStyle:{
            type:Object,
            default:() => ({
                slideRightWidth:"",
                itemWidth:""
            })
        }
    });
    const transform = computed(() => props.transform);
    const slideStyle = computed(() => props.slideStyle);
</script>
